DROP TABLE IF EXISTS MEMBER CASCADE;
DROP TABLE IF EXISTS MILESTONE CASCADE;
DROP TABLE IF EXISTS ASSIGNEE CASCADE;
DROP TABLE IF EXISTS ISSUE CASCADE;
DROP TABLE IF EXISTS LABEL CASCADE;
DROP TABLE IF EXISTS ISSUE_LABEL CASCADE;

CREATE TABLE MEMBER
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(45),
    FILE_URL VARCHAR(100)
);

CREATE TABLE MILESTONE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE       VARCHAR(45),
    DESCRIPTION TEXT,
    IS_OPEN     BIT,
    DUE_DATE    DATE
);

CREATE TABLE ISSUE
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    WRITER_ID        BIGINT,
    TITLE            VARCHAR(45),
    DESCRIPTION      TEXT,
    IS_OPEN          BIT,
    CREATE_DATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    MILESTONE_ID     BIGINT,
    FOREIGN KEY (MILESTONE_ID) REFERENCES MILESTONE (ID)
);

CREATE TABLE ASSIGNEE
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID BIGINT,
    ISSUE_ID  BIGINT,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ID)
);

CREATE TABLE LABEL
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE           VARCHAR(45),
    DESCRIPTION     TEXT,
    BG_COLOR_CODE   VARCHAR(8),
    FONT_COLOR_CODE VARCHAR(8)
);

CREATE TABLE ISSUE_LABEL
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    ISSUE_ID BIGINT,
    LABEL_ID BIGINT,
    FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ID),
    FOREIGN KEY (LABEL_ID) REFERENCES LABEL (ID)
);
