INSERT INTO MEMBER (NAME, FILE_URL)
VALUES ('poco', 'https://avatars.githubusercontent.com/u/101160636?s=40&v=4');
INSERT INTO MEMBER (NAME, FILE_URL)
VALUES ('하림', 'https://avatars.githubusercontent.com/u/90844696?s=40&v=4');
INSERT INTO MEMBER (NAME, FILE_URL)
VALUES ('만쥬', 'https://avatars.githubusercontent.com/u/20828490?s=40&v=4');
INSERT INTO MILESTONE (TITLE, DESCRIPTION, IS_OPEN)
VALUES ('마일스톤1', '마일스톤1', '0');
INSERT INTO MILESTONE (TITLE, DESCRIPTION, IS_OPEN)
VALUES ('마일스톤2', '마일스톤2', '0');
INSERT INTO ISSUE (TITLE, DESCRIPTION, IS_OPEN, WRITER_ID)
VALUES ('듀이입니다', '듀이는 테스트 중...', '1', '1');
INSERT INTO ISSUE (TITLE, DESCRIPTION, IS_OPEN, WRITER_ID, MILESTONE_ID)
VALUES ('만쥬입니다', '만쥬는 테스트 중...', '0', '1', '1');
INSERT INTO ISSUE (TITLE, DESCRIPTION, IS_OPEN, WRITER_ID, MILESTONE_ID)
VALUES ('코어입니다', '코어는 테스트 중...', '0', '2', '2');
INSERT INTO ISSUE (TITLE, DESCRIPTION, IS_OPEN, WRITER_ID, MILESTONE_ID)
VALUES ('해나입니다', '해나는 테스트 중...', '1', '2', '2');
INSERT INTO ISSUE (TITLE, DESCRIPTION, IS_OPEN, WRITER_ID, MILESTONE_ID)
VALUES ('하림입니다', '하림는 테스트 중...', '0', '3', '1');
INSERT INTO ISSUE (TITLE, DESCRIPTION, IS_OPEN, WRITER_ID, MILESTONE_ID)
VALUES ('다온입니다', '다온는 테스트 중...', '1', '3', '2');
INSERT INTO ISSUE (TITLE, DESCRIPTION, IS_OPEN, WRITER_ID, MILESTONE_ID)
VALUES ('포코입니다', '포코는 테스트 중...', '0', '1', '2');
INSERT INTO ASSIGNEE (MEMBER_ID, ISSUE_ID)
VALUES ('1', '1');
INSERT INTO ASSIGNEE (MEMBER_ID, ISSUE_ID)
VALUES ('3', '1');
INSERT INTO LABEL (TITLE, BG_COLOR_CODE)
VALUES ('FE', '#655CC7');
INSERT INTO LABEL (TITLE, BG_COLOR_CODE)
VALUES ('BUG', '#14D6B6');
INSERT INTO ISSUE_LABEL (LABEL_ID, ISSUE_ID)
VALUES ('1', '1');
INSERT INTO ISSUE_LABEL (LABEL_ID, ISSUE_ID)
VALUES ('2', '1');
