DROP TABLE IF EXISTS MEMBER, MILESTONE, ISSUE, ASSIGNEE, LABEL, ISSUE_LABEL CASCADE;

CREATE TABLE MEMBER
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(45) NOT NULL,
    FILE_URL VARCHAR(100)
);

CREATE TABLE MILESTONE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE       VARCHAR(45) NOT NULL,
    DESCRIPTION TEXT,
    IS_OPEN     BIT DEFAULT 1,
    DUE_DATE    DATE
);

CREATE TABLE ISSUE
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    WRITER_ID        BIGINT,
    TITLE            VARCHAR(45),
    DESCRIPTION      TEXT,
    IS_OPEN          BIT          DEFAULT 1,
    CREATE_DATE_TIME DATETIME     DEFAULT CURRENT_TIMESTAMP,
    FILE_URL         VARCHAR(100) DEFAULT NULL,
    MILESTONE_ID     BIGINT,
    FOREIGN KEY (MILESTONE_ID) REFERENCES MILESTONE (ID)
);

CREATE TABLE ASSIGNEE
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID BIGINT,
    ISSUE_ID  BIGINT,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ID)
);

CREATE TABLE LABEL
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE           VARCHAR(45) NOT NULL,
    DESCRIPTION     TEXT,
    BG_COLOR_CODE   VARCHAR(8)  NOT NULL,
    FONT_COLOR_CODE VARCHAR(8) DEFAULT '#FFFFFF'
);

CREATE TABLE ISSUE_LABEL
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    LABEL_ID BIGINT,
    ISSUE_ID BIGINT,
    FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ID),
    FOREIGN KEY (LABEL_ID) REFERENCES LABEL (ID),
    UNIQUE (LABEL_ID, ISSUE_ID)
);
